name: github-actions
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            THERAPY_DB_TEST: TEST
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python3 -m pip install pipenv
                  pipenv sync

            - run: pipenv run flake8
            - run: pipenv run pytest tests/
