name: github-actions
on: [push, pull_request]
jobs:
    test:
        name: test py${{ matrix.python-version }}
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.DUMMY_AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-2
            AWS_DEFAULT_OUTPUT: text
            THERAPY_NORM_DB_URL: http://localhost:8001
            TEST: THERAPY_TEST
        strategy:
            matrix:
              python-version: [3.8, 3.9]
        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python3 -m pip install tox

            - name: Build local DynamoDB
              run: |
                  chmod +x ./tests/scripts/dynamodb_build.bash
                  ./tests/scripts/dynamodb_build.bash

            - name: Run tests
              run: python3 -m tox -e githubactions
    lint:
        name: lint py${{ matrix.python-version }}
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.DUMMY_AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-2
            AWS_DEFAULT_OUTPUT: text
        strategy:
            matrix:
              python-version: ['3.8', '3.9', '3.10']
              tox-python-version: ['38', '39', '310']
              include:
                - python-version: '3.8'
                  tox-python-version: '38'
                - python-version: '3.9'
                  tox-python-version: '39'
                - python-version: '3.10'
                  tox-python-version: '310'
        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python3 -m pip install tox

            - name: Check style
              run: python3 -m tox -e py${{ matrix.tox-python-version }}-lint

            - name: Check type correctness
              if: ${{ always() }}
              run: python3 -m tox -e py${{ matrix.tox-python-version }}-mypy

