name: github-actions
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.DUMMY_AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-2
            AWS_DEFAULT_OUTPUT: text
            THERAPY_NORM_DB_URL: http://localhost:8001
            TEST: THERAPY_TEST
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python3 -m pip install pipenv
                  pipenv install --dev

            - name: Run tests
              run: python3 -m tox -e testdb

            - name: Check style
              run: python3 -m tox -e flake8

            - name: Check type correctness
              run: python3 -m tox -e mypy
