name: github-actions
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.DUMMY_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.DUMMY_AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-2
            AWS_DEFAULT_OUTPUT: text
            THERAPY_NORM_DB_URL: http://localhost:8001
            TEST: THERAPY_TEST
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python3 -m pip install -e ".[test]"

            - name: Build local DynamoDB
              run: |
                  chmod +x ./tests/scripts/dynamodb_build.bash
                  ./tests/scripts/dynamodb_build.bash

            - name: Check style
              run: pipenv run tox -e py38-lint

            - name: Check type correctness
              run: pipenv run tox -e py38-mypy

            - name: Run tests
              run: pipenv run tox -e githubactions
