name: github-actions
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python3 -m pip install pipenv
                  pipenv install --dev

            - run: chmod +x ./tests/unit/dynamodb_build.bash
            - run: ./tests/unit/dynamodb_build.bash
            - run: pipenv run flake8
            # - run: pipenv run pytest tests/
            - run: pipenv run pytest tests/unit/test_database.py
